name: gocreate
version: git
summary: Create .go Application Structure
description: Structuring Go Applications
confinement: strict
base: bare

parts:
  gocreate:
    plugin: go
    go-importpath: github.com/complexorganizations/gocreate
    source: .
    source-type: git
    build-packages:
      - gcc

apps:
  gocreate:
    command: bin/gocreate
