name: gocreate
version: "1.0.0"
summary: Create .go Application Structure
description: Structuring Go Applications
grade: stable
confinement: strict
license: unlicense
base: bare

parts:
  gocreate:
    plugin: go
    go-importpath: github.com/complexorganizations/gocreate
    source: .
    source-type: git

apps:
  gocreate:
    command: bin/gocreate
