name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Get dependencies
        run: go get .
      - name: Run Test
        run: go run main.go First_Project
      - name: Build Test
        run: go build .
      - name: Run the build
        run: ./gocreate Second_Project
